POST https://node-do-zero-habd.onrender.com/videos
Content-Type: application/json

{

    "title": "video node",
    "description": "Esse é o segundo vídeo",
    "duration": 400

}

###

GET https://node-do-zero-habd.onrender.com/videos?


###

PUT https://node-do-zero-habd.onrender.com/videos/ed8d8d73-40cb-41e4-b460-84436f8a565a
Content-Type: application/json

{

    "title": "video 2",
    "description": "Esse é o segundo vídeo",
    "duration": 290

}

###

DELETE https://node-do-zero-habd.onrender.com/videos/6caecc84-57d9-4ad1-80ad-3c78cb134516